dist: trusty
sudo: false

language: python

python:
  - "2.7"
  - "3.4"

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

addons:
  chrome: stable
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

services:
  - postgresql
  - redis

cache:
  pip: true
  yarn: true

before_install:
  # Update "pip" to latest stable release
  - pip install -U pip

  - nvm install 6
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  # Install SkyLines Python dependencies
  - pip install -e .

  # Install testing dependencies
  - pip install -r requirements.txt

  - cd ember
  - yarn install
  - bower install
  - cd ..

before_script:
  # Create the testing database
  - psql -U postgres -c 'CREATE DATABASE skylines_test;'

  # Install PostGIS extension into the database
  - psql -U postgres -d skylines_test -c 'CREATE EXTENSION postgis;'

  # Install fuzzystrmatch extension into the database
  - psql -U postgres -d skylines_test -c 'CREATE EXTENSION fuzzystrmatch;'

script:
  # Run the test suite
  - py.test -vv --cov=skylines --cov-report term-missing:skip-covered

  - cd ember
  - yarn test
